### PR TITLE
fix: resolve duplicate hasCompleted identifier in app initialization service

### PR DESCRIPTION
**Pull request by TheWildHustle**
## Summary
Rename the async method `hasCompleted()` to `getCompletionStatus()` to remove the duplicate identifier collision with the existing `hasCompleted` class property.

## Why
`AppInitializationService` currently declares both a property and method named `hasCompleted`, which triggers TS2300 duplicate identifier errors and blocks typecheck.

## Validation
- `npm run -s typecheck > /tmp/runstr-h11-typecheck.log 2>&1 || true`
- Confirmed `AppInitializationService.ts(21,11|233,9): error TS2300` is no longer present in log

## Risk
Low — method rename only, no behavior change.

## Rollback
Revert this PR commit to restore prior symbol name (and duplicate identifier behavior).

### CODE REVIEW

**Comment by TheWildHustle** [comment]
Closing: Stale base — main already uses _hasCompleted for the private field. The naming collision between the property and method still exists but doesn't cause runtime errors. Conflicts with #196.
